// Mocks generated by Mockito 5.4.6 from annotations
// in squad_app/test/mocks/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i17;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:firebase_storage/firebase_storage.dart' as _i18;
import 'package:flutter/material.dart' as _i29;
import 'package:image_picker/image_picker.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:squad_app/models/block_model.dart' as _i13;
import 'package:squad_app/models/group_model.dart' as _i2;
import 'package:squad_app/models/meetup_feedback.dart' as _i22;
import 'package:squad_app/models/message_model.dart' as _i3;
import 'package:squad_app/models/post_chat_message.dart' as _i4;
import 'package:squad_app/models/post_model.dart' as _i10;
import 'package:squad_app/models/report_model.dart' as _i24;
import 'package:squad_app/models/user_model.dart' as _i8;
import 'package:squad_app/services/account_deletion_service.dart' as _i26;
import 'package:squad_app/services/analytics_service.dart' as _i20;
import 'package:squad_app/services/auth_service.dart' as _i5;
import 'package:squad_app/services/block_service.dart' as _i12;
import 'package:squad_app/services/deep_link_service.dart' as _i28;
import 'package:squad_app/services/email_verification_service.dart' as _i27;
import 'package:squad_app/services/feedback_service.dart' as _i21;
import 'package:squad_app/services/firestore_service.dart' as _i14;
import 'package:squad_app/services/notification_service.dart' as _i19;
import 'package:squad_app/services/post_chat_service.dart' as _i25;
import 'package:squad_app/services/post_service.dart' as _i9;
import 'package:squad_app/services/report_service.dart' as _i23;
import 'package:squad_app/services/storage_service.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGroupModel_0 extends _i1.SmartFake implements _i2.GroupModel {
  _FakeGroupModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessageModel_1 extends _i1.SmartFake implements _i3.MessageModel {
  _FakeMessageModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostChatMessage_2 extends _i1.SmartFake
    implements _i4.PostChatMessage {
  _FakePostChatMessage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i7.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i6.Stream<_i7.User?>.empty(),
          )
          as _i6.Stream<_i7.User?>);

  @override
  _i6.Future<_i8.UserModel?> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<_i8.UserModel?>.value(),
          )
          as _i6.Future<_i8.UserModel?>);

  @override
  _i6.Future<_i8.UserModel?> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i6.Future<_i8.UserModel?>.value(),
          )
          as _i6.Future<_i8.UserModel?>);

  @override
  _i6.Future<_i8.UserModel?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i8.UserModel?>.value(),
          )
          as _i6.Future<_i8.UserModel?>);

  @override
  _i6.Future<_i8.UserModel?> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i6.Future<_i8.UserModel?>.value(),
          )
          as _i6.Future<_i8.UserModel?>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i8.UserModel?> getUserData(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [uid]),
            returnValue: _i6.Future<_i8.UserModel?>.value(),
          )
          as _i6.Future<_i8.UserModel?>);

  @override
  _i6.Future<void> updateUserProfile({
    String? displayName,
    String? photoUrl,
    String? bio,
    String? classYear,
    String? location,
    List<String>? interests,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #displayName: displayName,
              #photoUrl: photoUrl,
              #bio: bio,
              #classYear: classYear,
              #location: location,
              #interests: interests,
              #gender: gender,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isUsernameAvailable(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#isUsernameAvailable, [username]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> reauthenticateWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithGoogle, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> reauthenticateWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithApple, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> reauthenticateUser() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateUser, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [PostService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostService extends _i1.Mock implements _i9.PostService {
  MockPostService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> createPost(_i10.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [post]),
            returnValue: _i6.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createPost, [post]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Stream<List<_i10.Post>> getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Stream<List<_i10.Post>> getAllPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPosts, []),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Stream<List<_i10.Post>> getPostsByStatus(_i10.PostStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByStatus, [status]),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Stream<List<_i10.Post>> getUserPosts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPosts, [userId]),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Stream<List<_i10.Post>> getUpcomingPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingPosts, []),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Stream<List<_i10.Post>> getOngoingPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getOngoingPosts, []),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Future<void> joinPost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinPost, [postId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> leavePost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leavePost, [postId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePost(_i10.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [post]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> doesAuthorNeedFeedbackForDeletion(
    String? postId,
    String? authorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doesAuthorNeedFeedbackForDeletion, [
              postId,
              authorId,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> deletePostWithFeedback(
    String? postId,
    String? authorId, {
    bool? authorDidMeetup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deletePostWithFeedback,
              [postId, authorId],
              {#authorDidMeetup: authorDidMeetup},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> lockPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#lockPost, [postId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unlockPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockPost, [postId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i10.Post?> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i6.Future<_i10.Post?>.value(),
          )
          as _i6.Future<_i10.Post?>);

  @override
  _i6.Stream<List<_i10.Post>> searchPosts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPosts, [query]),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Stream<List<_i10.Post>> getPostsByGenderPreference(String? userGender) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByGenderPreference, [userGender]),
            returnValue: _i6.Stream<List<_i10.Post>>.empty(),
          )
          as _i6.Stream<List<_i10.Post>>);

  @override
  _i6.Future<void> updatePostStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#updatePostStatuses, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [BlockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockService extends _i1.Mock implements _i12.BlockService {
  MockBlockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> blockUser(String? targetUserId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [targetUserId], {#reason: reason}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unblockUser(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockUser, [targetUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isBlocked(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlocked, [userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isBlockedBy(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockedBy, [userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isBlockingRelationship(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockingRelationship, [userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i8.UserModel>> getBlockedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedUsers, []),
            returnValue: _i6.Future<List<_i8.UserModel>>.value(
              <_i8.UserModel>[],
            ),
          )
          as _i6.Future<List<_i8.UserModel>>);

  @override
  _i6.Stream<List<_i13.BlockModel>> getBlocksStream() =>
      (super.noSuchMethod(
            Invocation.method(#getBlocksStream, []),
            returnValue: _i6.Stream<List<_i13.BlockModel>>.empty(),
          )
          as _i6.Stream<List<_i13.BlockModel>>);

  @override
  List<_i8.UserModel> filterBlockedUsers(
    List<_i8.UserModel>? users,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterBlockedUsers, [
              users,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: <_i8.UserModel>[],
          )
          as List<_i8.UserModel>);

  @override
  bool shouldFilterContent(
    String? authorId,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldFilterContent, [
              authorId,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldCensorContent(
    String? authorId,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldCensorContent, [
              authorId,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldHideHangoutFromBlocked(
    String? hangoutHostId,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldHideHangoutFromBlocked, [
              hangoutHostId,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<bool> canAccessHangout(String? hangoutHostId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canAccessHangout, [hangoutHostId, userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i14.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i8.UserModel>> getGroupMembers(String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupMembers, [currentUserId]),
            returnValue: _i6.Future<List<_i8.UserModel>>.value(
              <_i8.UserModel>[],
            ),
          )
          as _i6.Future<List<_i8.UserModel>>);

  @override
  _i6.Stream<List<_i2.GroupModel>> getUserGroups(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGroups, [userId]),
            returnValue: _i6.Stream<List<_i2.GroupModel>>.empty(),
          )
          as _i6.Stream<List<_i2.GroupModel>>);

  @override
  _i6.Future<void> updateUserProfile({
    required String? userId,
    String? displayName,
    String? photoUrl,
    String? bio,
    int? age,
    String? location,
    List<String>? interests,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #userId: userId,
              #displayName: displayName,
              #photoUrl: photoUrl,
              #bio: bio,
              #age: age,
              #location: location,
              #interests: interests,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.GroupModel> createGroup({
    required String? name,
    required String? createdBy,
    String? description,
    String? imageUrl,
    List<String>? memberIds = const [],
    bool? isPrivate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [], {
              #name: name,
              #createdBy: createdBy,
              #description: description,
              #imageUrl: imageUrl,
              #memberIds: memberIds,
              #isPrivate: isPrivate,
            }),
            returnValue: _i6.Future<_i2.GroupModel>.value(
              _FakeGroupModel_0(
                this,
                Invocation.method(#createGroup, [], {
                  #name: name,
                  #createdBy: createdBy,
                  #description: description,
                  #imageUrl: imageUrl,
                  #memberIds: memberIds,
                  #isPrivate: isPrivate,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.GroupModel>);

  @override
  _i6.Future<void> addUserToGroup(String? groupId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addUserToGroup, [groupId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeUserFromGroup(String? groupId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserFromGroup, [groupId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<List<_i3.MessageModel>> getGroupMessages(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupMessages, [groupId]),
            returnValue: _i6.Stream<List<_i3.MessageModel>>.empty(),
          )
          as _i6.Stream<List<_i3.MessageModel>>);

  @override
  _i6.Future<_i3.MessageModel> sendMessage({
    required String? groupId,
    required String? senderId,
    required String? senderName,
    required String? content,
    _i3.MessageType? type = _i3.MessageType.text,
    String? senderAvatar,
    String? imageUrl,
    String? fileName,
    int? fileSize,
    String? replyToMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #groupId: groupId,
              #senderId: senderId,
              #senderName: senderName,
              #content: content,
              #type: type,
              #senderAvatar: senderAvatar,
              #imageUrl: imageUrl,
              #fileName: fileName,
              #fileSize: fileSize,
              #replyToMessageId: replyToMessageId,
            }),
            returnValue: _i6.Future<_i3.MessageModel>.value(
              _FakeMessageModel_1(
                this,
                Invocation.method(#sendMessage, [], {
                  #groupId: groupId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #content: content,
                  #type: type,
                  #senderAvatar: senderAvatar,
                  #imageUrl: imageUrl,
                  #fileName: fileName,
                  #fileSize: fileSize,
                  #replyToMessageId: replyToMessageId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.MessageModel>);

  @override
  _i6.Future<void> markMessageAsRead(
    String? groupId,
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [groupId, messageId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> editMessage(
    String? groupId,
    String? messageId,
    String? newContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [groupId, messageId, newContent]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessage(String? groupId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [groupId, messageId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.GroupModel?> getGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroup, [groupId]),
            returnValue: _i6.Future<_i2.GroupModel?>.value(),
          )
          as _i6.Future<_i2.GroupModel?>);

  @override
  _i6.Future<List<_i8.UserModel>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i6.Future<List<_i8.UserModel>>.value(
              <_i8.UserModel>[],
            ),
          )
          as _i6.Future<List<_i8.UserModel>>);

  @override
  _i6.Future<_i8.UserModel?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i6.Future<_i8.UserModel?>.value(),
          )
          as _i6.Future<_i8.UserModel?>);

  @override
  _i6.Future<void> removeMemberFromPost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMemberFromPost, [postId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i15.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String?> uploadProfileImage(
    String? userId,
    _i16.XFile? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [userId, imageFile]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> uploadGroupImage(
    String? groupId,
    _i16.XFile? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGroupImage, [groupId, imageFile]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> uploadMessageImage(
    String? groupId,
    _i16.XFile? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMessageImage, [groupId, imageFile]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> uploadFile(
    String? groupId,
    _i17.File? file,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [groupId, file, fileName]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<_i16.XFile?> pickImageFromGallery() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromGallery, []),
            returnValue: _i6.Future<_i16.XFile?>.value(),
          )
          as _i6.Future<_i16.XFile?>);

  @override
  _i6.Future<_i16.XFile?> pickImageFromCamera() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromCamera, []),
            returnValue: _i6.Future<_i16.XFile?>.value(),
          )
          as _i6.Future<_i16.XFile?>);

  @override
  _i6.Future<List<_i16.XFile>?> pickMultipleImages() =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleImages, []),
            returnValue: _i6.Future<List<_i16.XFile>?>.value(),
          )
          as _i6.Future<List<_i16.XFile>?>);

  @override
  _i6.Future<void> deleteFile(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [url]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteOldProfileImage(String? oldPhotoUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldProfileImage, [oldPhotoUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i18.UploadTask? uploadFileWithProgress(String? path, _i17.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFileWithProgress, [path, file]),
          )
          as _i18.UploadTask?);

  @override
  _i6.Stream<_i18.TaskSnapshot> uploadWithProgress(
    String? groupId,
    _i17.File? file,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadWithProgress, [groupId, file, fileName]),
            returnValue: _i6.Stream<_i18.TaskSnapshot>.empty(),
          )
          as _i6.Stream<_i18.TaskSnapshot>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i19.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onTokenRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onTokenRefresh, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void initializeTokenRefresh() => super.noSuchMethod(
    Invocation.method(#initializeTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> removeToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getCurrentToken() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unsubscribeFromTopics(List<String>? topics) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopics, [topics]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> subscribeToHangoutTopicsBasedOnGender(String? gender) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToHangoutTopicsBasedOnGender, [gender]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> subscribeToGenderSpecificTopic(String? gender) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToGenderSpecificTopic, [gender]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void initializeMessageHandlers() => super.noSuchMethod(
    Invocation.method(#initializeMessageHandlers, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> notifyHangoutOwnerOfJoin({
    required String? hangoutId,
    required String? ownerId,
    required String? joinerName,
    required String? joinerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutOwnerOfJoin, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #joinerName: joinerName,
              #joinerId: joinerId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> notifyHangoutOwnerOfLeave({
    required String? hangoutId,
    required String? ownerId,
    required String? leaverName,
    required String? leaverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutOwnerOfLeave, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #leaverName: leaverName,
              #leaverId: leaverId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> notifyHangoutUpdated({
    required String? hangoutId,
    required String? ownerId,
    required List<String>? participantIds,
    required List<String>? changes,
    String? oldDescription,
    DateTime? oldTime,
    String? oldLocation,
    String? newDescription,
    DateTime? newTime,
    String? newLocation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutUpdated, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #participantIds: participantIds,
              #changes: changes,
              #oldDescription: oldDescription,
              #oldTime: oldTime,
              #oldLocation: oldLocation,
              #newDescription: newDescription,
              #newTime: newTime,
              #newLocation: newLocation,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleHangoutChatNotifications(
    String? hangoutId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleHangoutChatNotifications, [
              hangoutId,
              enabled,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> getHangoutChatNotificationPreference(String? hangoutId) =>
      (super.noSuchMethod(
            Invocation.method(#getHangoutChatNotificationPreference, [
              hangoutId,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i20.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> isConsentGiven() =>
      (super.noSuchMethod(
            Invocation.method(#isConsentGiven, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void disable() => super.noSuchMethod(
    Invocation.method(#disable, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> trackHangoutCreated({
    required String? userId,
    required String? hangoutId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackHangoutCreated, [], {
              #userId: userId,
              #hangoutId: hangoutId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> trackHangoutJoined({
    required String? userId,
    required String? hangoutId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackHangoutJoined, [], {
              #userId: userId,
              #hangoutId: hangoutId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> trackMeetupSuccess({
    required bool? didMeetup,
    required String? hangoutId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMeetupSuccess, [], {
              #didMeetup: didMeetup,
              #hangoutId: hangoutId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> trackUserSignUp({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#trackUserSignUp, [], {#userId: userId}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [FeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackService extends _i1.Mock implements _i21.FeedbackService {
  MockFeedbackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> createFeedbackPromptForAuthor(_i10.Post? completedPost) =>
      (super.noSuchMethod(
            Invocation.method(#createFeedbackPromptForAuthor, [completedPost]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<List<_i22.PendingFeedbackPrompt>> getPendingFeedbackPrompts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingFeedbackPrompts, [userId]),
            returnValue: _i6.Stream<List<_i22.PendingFeedbackPrompt>>.empty(),
          )
          as _i6.Stream<List<_i22.PendingFeedbackPrompt>>);

  @override
  _i6.Future<void> markPromptAsShown(String? promptId) =>
      (super.noSuchMethod(
            Invocation.method(#markPromptAsShown, [promptId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> hasAuthorProvidedFeedback(
    String? hangoutId,
    String? authorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasAuthorProvidedFeedback, [
              hangoutId,
              authorId,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> submitFeedback({
    required String? hangoutId,
    required String? userId,
    required bool? didMeetup,
    String? additionalFeedback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitFeedback, [], {
              #hangoutId: hangoutId,
              #userId: userId,
              #didMeetup: didMeetup,
              #additionalFeedback: additionalFeedback,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> getFeedbackStats() =>
      (super.noSuchMethod(
            Invocation.method(#getFeedbackStats, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<void> cleanupOldPendingPrompts() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldPendingPrompts, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i22.MeetupFeedback>> getFeedbackForHangout(
    String? hangoutId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedbackForHangout, [hangoutId]),
            returnValue: _i6.Future<List<_i22.MeetupFeedback>>.value(
              <_i22.MeetupFeedback>[],
            ),
          )
          as _i6.Future<List<_i22.MeetupFeedback>>);

  @override
  _i6.Future<void> createTestFeedbackPrompts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#createTestFeedbackPrompts, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearTestFeedbackPrompts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearTestFeedbackPrompts, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ReportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportService extends _i1.Mock implements _i23.ReportService {
  MockReportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> submitReport({
    required String? contentType,
    required String? contentId,
    required String? contentTitle,
    required String? authorId,
    required Map<String, dynamic>? contentSnippet,
    required _i24.ReportReason? reason,
    required String? reporterUid,
    required String? reporterDisplayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitReport, [], {
              #contentType: contentType,
              #contentId: contentId,
              #contentTitle: contentTitle,
              #authorId: authorId,
              #contentSnippet: contentSnippet,
              #reason: reason,
              #reporterUid: reporterUid,
              #reporterDisplayName: reporterDisplayName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [PostChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostChatService extends _i1.Mock implements _i25.PostChatService {
  MockPostChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<List<_i4.PostChatMessage>> getChatMessages(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [postId]),
            returnValue: _i6.Stream<List<_i4.PostChatMessage>>.empty(),
          )
          as _i6.Stream<List<_i4.PostChatMessage>>);

  @override
  _i6.Future<_i4.PostChatMessage> sendMessage({
    required String? postId,
    required String? senderId,
    required String? senderName,
    required String? content,
    String? senderPhotoUrl,
    _i4.PostChatMessageType? type = _i4.PostChatMessageType.text,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #postId: postId,
              #senderId: senderId,
              #senderName: senderName,
              #content: content,
              #senderPhotoUrl: senderPhotoUrl,
              #type: type,
              #imageUrl: imageUrl,
            }),
            returnValue: _i6.Future<_i4.PostChatMessage>.value(
              _FakePostChatMessage_2(
                this,
                Invocation.method(#sendMessage, [], {
                  #postId: postId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #content: content,
                  #senderPhotoUrl: senderPhotoUrl,
                  #type: type,
                  #imageUrl: imageUrl,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.PostChatMessage>);

  @override
  _i6.Future<_i4.PostChatMessage> sendSystemMessage({
    required String? postId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSystemMessage, [], {
              #postId: postId,
              #content: content,
            }),
            returnValue: _i6.Future<_i4.PostChatMessage>.value(
              _FakePostChatMessage_2(
                this,
                Invocation.method(#sendSystemMessage, [], {
                  #postId: postId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.PostChatMessage>);

  @override
  _i6.Future<void> markMessagesAsRead(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [postId, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getUnreadCount(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [postId, userId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> editMessage({
    required String? postId,
    required String? messageId,
    required String? newContent,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [], {
              #postId: postId,
              #messageId: messageId,
              #newContent: newContent,
              #userId: userId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessage({
    required String? postId,
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [], {
              #postId: postId,
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initializeChat(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#initializeChat, [postId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> handleUserJoined({
    required String? postId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleUserJoined, [], {
              #postId: postId,
              #userName: userName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> handleUserLeft({
    required String? postId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleUserLeft, [], {
              #postId: postId,
              #userName: userName,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> archiveChat(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveChat, [postId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cleanupOldChats() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldChats, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> canAccessChat(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canAccessChat, [postId, userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isChatReadOnly(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#isChatReadOnly, [postId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [AccountDeletionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountDeletionService extends _i1.Mock
    implements _i26.AccountDeletionService {
  MockAccountDeletionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> revokeNotificationTokens(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeNotificationTokens, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> revokeAppleSignInToken(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeAppleSignInToken, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<String> deleteUserAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAccount, [userId]),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);

  @override
  _i6.Future<bool> hasActiveSubscriptions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveSubscriptions, [userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> scheduleAccountDeletion(
    String? userId,
    DateTime? deletionDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleAccountDeletion, [userId, deletionDate]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelScheduledDeletion(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelScheduledDeletion, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [EmailVerificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailVerificationService extends _i1.Mock
    implements _i27.EmailVerificationService {
  MockEmailVerificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> sendVerificationCode(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendVerificationCode, [email]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> validateCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#validateCode, [code]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> canResendCode() =>
      (super.noSuchMethod(
            Invocation.method(#canResendCode, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int> getResendCooldownSeconds() =>
      (super.noSuchMethod(
            Invocation.method(#getResendCooldownSeconds, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  bool isValidBUEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isValidBUEmail, [email]),
            returnValue: false,
          )
          as bool);

  @override
  String getDisplayErrorMessage(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayErrorMessage, [error]),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getDisplayErrorMessage, [error]),
            ),
          )
          as String);

  @override
  _i6.Future<void> testConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testConnection, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DeepLinkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeepLinkService extends _i1.Mock implements _i28.DeepLinkService {
  MockDeepLinkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize(_i29.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [context]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
