// Mocks generated by Mockito 5.4.6 from annotations
// in squad_app/test/widget/widgets/post_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:squad_app/models/matching_profile.dart' as _i5;
import 'package:squad_app/models/post_model.dart' as _i8;
import 'package:squad_app/models/user_model.dart' as _i4;
import 'package:squad_app/providers/auth_provider.dart' as _i2;
import 'package:squad_app/providers/post_provider.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get accountDeletionCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#accountDeletionCompleted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithEmailPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile({
    String? displayName,
    String? photoUrl,
    String? bio,
    String? classYear,
    String? location,
    List<String>? interests,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoUrl: photoUrl,
              #bio: bio,
              #classYear: classYear,
              #location: location,
              #interests: interests,
              #gender: gender,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCurrentUser(_i4.UserModel? updatedUser) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentUser, [updatedUser]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> refreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMatchingProfile(_i5.MatchingProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateMatchingProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleMatchingActive(bool? isActive) =>
      (super.noSuchMethod(
            Invocation.method(#toggleMatchingActive, [isActive]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> checkUsernameAvailability(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#checkUsernameAvailability, [username]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetAccountDeletionFlag() => super.noSuchMethod(
    Invocation.method(#resetAccountDeletionFlag, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> reauthenticateUser() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateUser, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasActiveSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveSubscriptions, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<String> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Stream<String>.empty(),
            returnValueForMissingStub: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Future<void> scheduleAccountDeletion(DateTime? deletionDate) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleAccountDeletion, [deletionDate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelScheduledDeletion() =>
      (super.noSuchMethod(
            Invocation.method(#cancelScheduledDeletion, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PostProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostProvider extends _i1.Mock implements _i7.PostProvider {
  @override
  List<_i8.Post> get posts =>
      (super.noSuchMethod(
            Invocation.getter(#posts),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  List<_i8.Post> get allPosts =>
      (super.noSuchMethod(
            Invocation.getter(#allPosts),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  List<_i8.Post> get upcomingPosts =>
      (super.noSuchMethod(
            Invocation.getter(#upcomingPosts),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  List<_i8.Post> get ongoingPosts =>
      (super.noSuchMethod(
            Invocation.getter(#ongoingPosts),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  List<_i8.Post> get userPosts =>
      (super.noSuchMethod(
            Invocation.getter(#userPosts),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void initializeForUser(String? userId) => super.noSuchMethod(
    Invocation.method(#initializeForUser, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> loadUserPosts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserPosts, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> createPost({
    required _i8.PostType? type,
    required String? authorId,
    required String? authorName,
    String? authorDorm,
    String? authorYear,
    required List<String>? genderPreferences,
    String? description,
    DateTime? scheduledTime,
    _i8.Activity? activity,
    String? customActivity,
    String? location,
    String? locationTo,
    int? maxParticipants,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #type: type,
              #authorId: authorId,
              #authorName: authorName,
              #authorDorm: authorDorm,
              #authorYear: authorYear,
              #genderPreferences: genderPreferences,
              #description: description,
              #scheduledTime: scheduledTime,
              #activity: activity,
              #customActivity: customActivity,
              #location: location,
              #locationTo: locationTo,
              #maxParticipants: maxParticipants,
            }),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> joinPost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinPost, [postId, userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> leavePost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leavePost, [postId, userId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updatePost(_i8.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [post]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> doesAuthorNeedFeedbackForDeletion(
    String? postId,
    String? authorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doesAuthorNeedFeedbackForDeletion, [
              postId,
              authorId,
            ]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deletePostWithFeedback(
    String? postId,
    String? authorId, {
    bool? authorDidMeetup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deletePostWithFeedback,
              [postId, authorId],
              {#authorDidMeetup: authorDidMeetup},
            ),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> lockPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#lockPost, [postId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> unlockPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockPost, [postId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  List<_i8.Post> getPostsForUser(String? userGender) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsForUser, [userGender]),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  List<_i8.Post> getUpcomingPostsForUser(String? userGender) =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingPostsForUser, [userGender]),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  List<_i8.Post> getOngoingPostsForUser(String? userGender) =>
      (super.noSuchMethod(
            Invocation.method(#getOngoingPostsForUser, [userGender]),
            returnValue: <_i8.Post>[],
            returnValueForMissingStub: <_i8.Post>[],
          )
          as List<_i8.Post>);

  @override
  _i3.Stream<List<_i8.Post>> searchPosts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPosts, [query]),
            returnValue: _i3.Stream<List<_i8.Post>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i8.Post>>.empty(),
          )
          as _i3.Stream<List<_i8.Post>>);

  @override
  _i3.Future<void> updatePostStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#updatePostStatuses, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool canUserJoinPost(_i8.Post? post, String? userId, {String? userGender}) =>
      (super.noSuchMethod(
            Invocation.method(
              #canUserJoinPost,
              [post, userId],
              {#userGender: userGender},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Post? getPostById(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValueForMissingStub: null,
          )
          as _i8.Post?);

  @override
  void setCurrentUser(_i4.UserModel? user) => super.noSuchMethod(
    Invocation.method(#setCurrentUser, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void cleanup() => super.noSuchMethod(
    Invocation.method(#cleanup, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
