// Mocks generated by Mockito 5.4.6 from annotations
// in squad_app/test/unit/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:firebase_analytics/firebase_analytics.dart' as _i5;
import 'package:firebase_analytics_platform_interface/firebase_analytics_platform_interface.dart'
    as _i7;
import 'package:firebase_auth/firebase_auth.dart' as _i12;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i13;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_crashlytics/firebase_crashlytics.dart' as _i8;
import 'package:flutter/foundation.dart' as _i9;
import 'package:google_sign_in/google_sign_in.dart' as _i3;
import 'package:google_sign_in/src/event_types.dart' as _i10;
import 'package:google_sign_in/src/token_types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInAuthorizationClient_1 extends _i1.SmartFake
    implements _i3.GoogleSignInAuthorizationClient {
  _FakeGoogleSignInAuthorizationClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGoogleSignInAccount_2 extends _i1.SmartFake
    implements _i3.GoogleSignInAccount {
  _FakeGoogleSignInAccount_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInAuthentication_3 extends _i1.SmartFake
    implements _i4.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAnalytics extends _i1.Mock implements _i5.FirebaseAnalytics {
  MockFirebaseAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  _i6.Future<String?> get appInstanceId =>
      (super.noSuchMethod(
            Invocation.getter(#appInstanceId),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i6.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int?> getSessionId() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionId, []),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setConsent({
    bool? adStorageConsentGranted,
    bool? analyticsStorageConsentGranted,
    bool? adPersonalizationSignalsConsentGranted,
    bool? adUserDataConsentGranted,
    bool? functionalityStorageConsentGranted,
    bool? personalizationStorageConsentGranted,
    bool? securityStorageConsentGranted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setConsent, [], {
              #adStorageConsentGranted: adStorageConsentGranted,
              #analyticsStorageConsentGranted: analyticsStorageConsentGranted,
              #adPersonalizationSignalsConsentGranted:
                  adPersonalizationSignalsConsentGranted,
              #adUserDataConsentGranted: adUserDataConsentGranted,
              #functionalityStorageConsentGranted:
                  functionalityStorageConsentGranted,
              #personalizationStorageConsentGranted:
                  personalizationStorageConsentGranted,
              #securityStorageConsentGranted: securityStorageConsentGranted,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setDefaultEventParameters(
    Map<String, Object?>? defaultParameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultEventParameters, [defaultParameters]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setAnalyticsCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAnalyticsCollectionEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setUserId({
    String? id,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserId, [], {
              #id: id,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setCurrentScreen({
    required String? screenName,
    String? screenClassOverride = 'Flutter',
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentScreen, [], {
              #screenName: screenName,
              #screenClassOverride: screenClassOverride,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setUserProperty({
    required String? name,
    required String? value,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetAnalyticsData() =>
      (super.noSuchMethod(
            Invocation.method(#resetAnalyticsData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAddPaymentInfo({
    String? coupon,
    String? currency,
    String? paymentType,
    double? value,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddPaymentInfo, [], {
              #coupon: coupon,
              #currency: currency,
              #paymentType: paymentType,
              #value: value,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAddShippingInfo({
    String? coupon,
    String? currency,
    double? value,
    String? shippingTier,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddShippingInfo, [], {
              #coupon: coupon,
              #currency: currency,
              #value: value,
              #shippingTier: shippingTier,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAddToCart({
    List<_i7.AnalyticsEventItem>? items,
    double? value,
    String? currency,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddToCart, [], {
              #items: items,
              #value: value,
              #currency: currency,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAddToWishlist({
    List<_i7.AnalyticsEventItem>? items,
    double? value,
    String? currency,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAddToWishlist, [], {
              #items: items,
              #value: value,
              #currency: currency,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAdImpression({
    String? adPlatform,
    String? adSource,
    String? adFormat,
    String? adUnitName,
    double? value,
    String? currency,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAdImpression, [], {
              #adPlatform: adPlatform,
              #adSource: adSource,
              #adFormat: adFormat,
              #adUnitName: adUnitName,
              #value: value,
              #currency: currency,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logAppOpen({
    _i7.AnalyticsCallOptions? callOptions,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logAppOpen, [], {
              #callOptions: callOptions,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logBeginCheckout({
    double? value,
    String? currency,
    List<_i7.AnalyticsEventItem>? items,
    String? coupon,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logBeginCheckout, [], {
              #value: value,
              #currency: currency,
              #items: items,
              #coupon: coupon,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logCampaignDetails({
    required String? source,
    required String? medium,
    required String? campaign,
    String? term,
    String? content,
    String? aclid,
    String? cp1,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logCampaignDetails, [], {
              #source: source,
              #medium: medium,
              #campaign: campaign,
              #term: term,
              #content: content,
              #aclid: aclid,
              #cp1: cp1,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logEarnVirtualCurrency({
    required String? virtualCurrencyName,
    required num? value,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEarnVirtualCurrency, [], {
              #virtualCurrencyName: virtualCurrencyName,
              #value: value,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logGenerateLead({
    String? currency,
    double? value,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logGenerateLead, [], {
              #currency: currency,
              #value: value,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logJoinGroup({
    required String? groupId,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logJoinGroup, [], {
              #groupId: groupId,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logLevelUp({
    required int? level,
    String? character,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLevelUp, [], {
              #level: level,
              #character: character,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logLevelStart({
    required String? levelName,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLevelStart, [], {
              #levelName: levelName,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logLevelEnd({
    required String? levelName,
    int? success,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLevelEnd, [], {
              #levelName: levelName,
              #success: success,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSetCheckoutOption({
    required int? checkoutStep,
    required String? checkoutOption,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSetCheckoutOption, [], {
              #checkoutStep: checkoutStep,
              #checkoutOption: checkoutOption,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logLogin({
    String? loginMethod,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logLogin, [], {
              #loginMethod: loginMethod,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logPostScore({
    required int? score,
    int? level,
    String? character,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPostScore, [], {
              #score: score,
              #level: level,
              #character: character,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logPurchase({
    String? currency,
    String? coupon,
    double? value,
    List<_i7.AnalyticsEventItem>? items,
    double? tax,
    double? shipping,
    String? transactionId,
    String? affiliation,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logPurchase, [], {
              #currency: currency,
              #coupon: coupon,
              #value: value,
              #items: items,
              #tax: tax,
              #shipping: shipping,
              #transactionId: transactionId,
              #affiliation: affiliation,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logRemoveFromCart({
    String? currency,
    double? value,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logRemoveFromCart, [], {
              #currency: currency,
              #value: value,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logScreenView({
    String? screenClass,
    String? screenName,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenClass: screenClass,
              #screenName: screenName,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSelectItem({
    String? itemListId,
    String? itemListName,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectItem, [], {
              #itemListId: itemListId,
              #itemListName: itemListName,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSelectPromotion({
    String? creativeName,
    String? creativeSlot,
    List<_i7.AnalyticsEventItem>? items,
    String? locationId,
    String? promotionId,
    String? promotionName,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectPromotion, [], {
              #creativeName: creativeName,
              #creativeSlot: creativeSlot,
              #items: items,
              #locationId: locationId,
              #promotionId: promotionId,
              #promotionName: promotionName,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewCart({
    String? currency,
    double? value,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewCart, [], {
              #currency: currency,
              #value: value,
              #items: items,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSearch({
    required String? searchTerm,
    int? numberOfNights,
    int? numberOfRooms,
    int? numberOfPassengers,
    String? origin,
    String? destination,
    String? startDate,
    String? endDate,
    String? travelClass,
    Map<String, Object>? parameters,
    _i7.AnalyticsCallOptions? callOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSearch, [], {
              #searchTerm: searchTerm,
              #numberOfNights: numberOfNights,
              #numberOfRooms: numberOfRooms,
              #numberOfPassengers: numberOfPassengers,
              #origin: origin,
              #destination: destination,
              #startDate: startDate,
              #endDate: endDate,
              #travelClass: travelClass,
              #parameters: parameters,
              #callOptions: callOptions,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSelectContent({
    required String? contentType,
    required String? itemId,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSelectContent, [], {
              #contentType: contentType,
              #itemId: itemId,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logShare({
    required String? contentType,
    required String? itemId,
    required String? method,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logShare, [], {
              #contentType: contentType,
              #itemId: itemId,
              #method: method,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSignUp({
    required String? signUpMethod,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSignUp, [], {
              #signUpMethod: signUpMethod,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logSpendVirtualCurrency({
    required String? itemName,
    required String? virtualCurrencyName,
    required num? value,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSpendVirtualCurrency, [], {
              #itemName: itemName,
              #virtualCurrencyName: virtualCurrencyName,
              #value: value,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logTutorialBegin({Map<String, Object>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logTutorialBegin, [], {#parameters: parameters}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logTutorialComplete({Map<String, Object>? parameters}) =>
      (super.noSuchMethod(
            Invocation.method(#logTutorialComplete, [], {
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logUnlockAchievement({
    required String? id,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logUnlockAchievement, [], {
              #id: id,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewItem({
    String? currency,
    double? value,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItem, [], {
              #currency: currency,
              #value: value,
              #items: items,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewItemList({
    List<_i7.AnalyticsEventItem>? items,
    String? itemListId,
    String? itemListName,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewItemList, [], {
              #items: items,
              #itemListId: itemListId,
              #itemListName: itemListName,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewPromotion({
    String? creativeName,
    String? creativeSlot,
    List<_i7.AnalyticsEventItem>? items,
    String? locationId,
    String? promotionId,
    String? promotionName,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewPromotion, [], {
              #creativeName: creativeName,
              #creativeSlot: creativeSlot,
              #items: items,
              #locationId: locationId,
              #promotionId: promotionId,
              #promotionName: promotionName,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logViewSearchResults({
    required String? searchTerm,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logViewSearchResults, [], {
              #searchTerm: searchTerm,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logRefund({
    String? currency,
    String? coupon,
    double? value,
    double? tax,
    double? shipping,
    String? transactionId,
    String? affiliation,
    List<_i7.AnalyticsEventItem>? items,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logRefund, [], {
              #currency: currency,
              #coupon: coupon,
              #value: value,
              #tax: tax,
              #shipping: shipping,
              #transactionId: transactionId,
              #affiliation: affiliation,
              #items: items,
              #parameters: parameters,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSessionTimeoutDuration(Duration? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setSessionTimeoutDuration, [timeout]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initiateOnDeviceConversionMeasurementWithEmailAddress(
    String? emailAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithEmailAddress,
              [emailAddress],
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initiateOnDeviceConversionMeasurementWithPhoneNumber(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithPhoneNumber,
              [phoneNumber],
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initiateOnDeviceConversionMeasurementWithHashedEmailAddress(
    String? hashedEmailAddress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithHashedEmailAddress,
              [hashedEmailAddress],
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initiateOnDeviceConversionMeasurementWithHashedPhoneNumber(
    String? hashedPhoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(
              #initiateOnDeviceConversionMeasurementWithHashedPhoneNumber,
              [hashedPhoneNumber],
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [FirebaseCrashlytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseCrashlytics extends _i1.Mock
    implements _i8.FirebaseCrashlytics {
  MockFirebaseCrashlytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  bool get isCrashlyticsCollectionEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isCrashlyticsCollectionEnabled),
            returnValue: false,
          )
          as bool);

  @override
  set app(_i2.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i6.Future<bool> checkForUnsentReports() =>
      (super.noSuchMethod(
            Invocation.method(#checkForUnsentReports, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void crash() => super.noSuchMethod(
    Invocation.method(#crash, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> deleteUnsentReports() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnsentReports, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> didCrashOnPreviousExecution() =>
      (super.noSuchMethod(
            Invocation.method(#didCrashOnPreviousExecution, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> recordError(
    dynamic exception,
    StackTrace? stack, {
    dynamic reason,
    Iterable<Object>? information = const [],
    bool? printDetails,
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordError,
              [exception, stack],
              {
                #reason: reason,
                #information: information,
                #printDetails: printDetails,
                #fatal: fatal,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> recordFlutterError(
    _i9.FlutterErrorDetails? flutterErrorDetails, {
    bool? fatal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordFlutterError,
              [flutterErrorDetails],
              {#fatal: fatal},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> recordFlutterFatalError(
    _i9.FlutterErrorDetails? flutterErrorDetails,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordFlutterFatalError, [flutterErrorDetails]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> log(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#log, [message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendUnsentReports() =>
      (super.noSuchMethod(
            Invocation.method(#sendUnsentReports, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setCrashlyticsCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setCrashlyticsCollectionEnabled, [enabled]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setUserIdentifier(String? identifier) =>
      (super.noSuchMethod(
            Invocation.method(#setUserIdentifier, [identifier]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setCustomKey(String? key, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomKey, [key, value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i3.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i10.GoogleSignInAuthenticationEvent> get authenticationEvents =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationEvents),
            returnValue:
                _i6.Stream<_i10.GoogleSignInAuthenticationEvent>.empty(),
          )
          as _i6.Stream<_i10.GoogleSignInAuthenticationEvent>);

  @override
  _i3.GoogleSignInAuthorizationClient get authorizationClient =>
      (super.noSuchMethod(
            Invocation.getter(#authorizationClient),
            returnValue: _FakeGoogleSignInAuthorizationClient_1(
              this,
              Invocation.getter(#authorizationClient),
            ),
          )
          as _i3.GoogleSignInAuthorizationClient);

  @override
  _i6.Future<void> initialize({
    String? clientId,
    String? serverClientId,
    String? nonce,
    String? hostedDomain,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #clientId: clientId,
              #serverClientId: serverClientId,
              #nonce: nonce,
              #hostedDomain: hostedDomain,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.GoogleSignInAccount?>? attemptLightweightAuthentication({
    bool? reportAllExceptions = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#attemptLightweightAuthentication, [], {
              #reportAllExceptions: reportAllExceptions,
            }),
          )
          as _i6.Future<_i3.GoogleSignInAccount?>?);

  @override
  bool supportsAuthenticate() =>
      (super.noSuchMethod(
            Invocation.method(#supportsAuthenticate, []),
            returnValue: false,
          )
          as bool);

  @override
  bool authorizationRequiresUserInteraction() =>
      (super.noSuchMethod(
            Invocation.method(#authorizationRequiresUserInteraction, []),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<_i3.GoogleSignInAccount> authenticate({
    List<String>? scopeHint = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {#scopeHint: scopeHint}),
            returnValue: _i6.Future<_i3.GoogleSignInAccount>.value(
              _FakeGoogleSignInAccount_2(
                this,
                Invocation.method(#authenticate, [], {#scopeHint: scopeHint}),
              ),
            ),
          )
          as _i6.Future<_i3.GoogleSignInAccount>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAccount extends _i1.Mock
    implements _i3.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i11.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i4.GoogleSignInAuthentication get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _FakeGoogleSignInAuthentication_3(
              this,
              Invocation.getter(#authentication),
            ),
          )
          as _i4.GoogleSignInAuthentication);

  @override
  _i3.GoogleSignInAuthorizationClient get authorizationClient =>
      (super.noSuchMethod(
            Invocation.getter(#authorizationClient),
            returnValue: _FakeGoogleSignInAuthorizationClient_1(
              this,
              Invocation.getter(#authorizationClient),
            ),
          )
          as _i3.GoogleSignInAuthorizationClient);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i4.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i12.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [UserInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInfo extends _i1.Mock implements _i13.UserInfo {
  MockUserInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerId =>
      (super.noSuchMethod(
            Invocation.getter(#providerId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#providerId),
            ),
          )
          as String);
}
