// Mocks generated by Mockito 5.4.6 from annotations
// in squad_app/test/unit/services/post_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:squad_app/models/chat_message.dart' as _i2;
import 'package:squad_app/models/meetup_feedback.dart' as _i9;
import 'package:squad_app/models/post_model.dart' as _i8;
import 'package:squad_app/models/user_model.dart' as _i6;
import 'package:squad_app/services/analytics_service.dart' as _i10;
import 'package:squad_app/services/chat_service.dart' as _i3;
import 'package:squad_app/services/feedback_service.dart' as _i7;
import 'package:squad_app/services/firestore_service.dart' as _i5;
import 'package:squad_app/services/notification_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatMessage_0 extends _i1.SmartFake implements _i2.ChatMessage {
  _FakeChatMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatService extends _i1.Mock implements _i3.ChatService {
  MockChatService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.ChatMessage>> getMessages(
    _i2.ChatContext? context,
    String? chatRoomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [context, chatRoomId]),
            returnValue: _i4.Stream<List<_i2.ChatMessage>>.empty(),
          )
          as _i4.Stream<List<_i2.ChatMessage>>);

  @override
  _i4.Future<_i2.ChatMessage> sendMessage({
    required _i2.ChatContext? context,
    required String? chatRoomId,
    required String? senderId,
    required String? senderName,
    required String? content,
    String? senderPhotoUrl,
    _i2.ChatMessageType? type = _i2.ChatMessageType.text,
    String? imageUrl,
    String? replyToMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #context: context,
              #chatRoomId: chatRoomId,
              #senderId: senderId,
              #senderName: senderName,
              #content: content,
              #senderPhotoUrl: senderPhotoUrl,
              #type: type,
              #imageUrl: imageUrl,
              #replyToMessageId: replyToMessageId,
            }),
            returnValue: _i4.Future<_i2.ChatMessage>.value(
              _FakeChatMessage_0(
                this,
                Invocation.method(#sendMessage, [], {
                  #context: context,
                  #chatRoomId: chatRoomId,
                  #senderId: senderId,
                  #senderName: senderName,
                  #content: content,
                  #senderPhotoUrl: senderPhotoUrl,
                  #type: type,
                  #imageUrl: imageUrl,
                  #replyToMessageId: replyToMessageId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChatMessage>);

  @override
  _i4.Future<_i2.ChatMessage> sendSystemMessage({
    required _i2.ChatContext? context,
    required String? chatRoomId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSystemMessage, [], {
              #context: context,
              #chatRoomId: chatRoomId,
              #content: content,
            }),
            returnValue: _i4.Future<_i2.ChatMessage>.value(
              _FakeChatMessage_0(
                this,
                Invocation.method(#sendSystemMessage, [], {
                  #context: context,
                  #chatRoomId: chatRoomId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChatMessage>);

  @override
  _i4.Future<void> markMessagesAsRead(
    _i2.ChatContext? context,
    String? chatRoomId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [
              context,
              chatRoomId,
              userId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getUnreadCount(
    _i2.ChatContext? context,
    String? chatRoomId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [context, chatRoomId, userId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> editMessage({
    required _i2.ChatContext? context,
    required String? chatRoomId,
    required String? messageId,
    required String? newContent,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [], {
              #context: context,
              #chatRoomId: chatRoomId,
              #messageId: messageId,
              #newContent: newContent,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessage({
    required _i2.ChatContext? context,
    required String? chatRoomId,
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [], {
              #context: context,
              #chatRoomId: chatRoomId,
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initializeChat(
    _i2.ChatContext? context,
    String? chatRoomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initializeChat, [context, chatRoomId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initializeMatchedGroupChat(
    String? chatRoomId,
    String? sharedInterests,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initializeMatchedGroupChat, [
              chatRoomId,
              sharedInterests,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleUserJoined({
    required _i2.ChatContext? context,
    required String? chatRoomId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleUserJoined, [], {
              #context: context,
              #chatRoomId: chatRoomId,
              #userName: userName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleUserLeft({
    required _i2.ChatContext? context,
    required String? chatRoomId,
    required String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleUserLeft, [], {
              #context: context,
              #chatRoomId: chatRoomId,
              #userName: userName,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> archiveChat(_i2.ChatContext? context, String? chatRoomId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveChat, [context, chatRoomId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> canAccessChat(
    _i2.ChatContext? context,
    String? chatRoomId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#canAccessChat, [context, chatRoomId, userId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isChatReadOnly(
    _i2.ChatContext? context,
    String? chatRoomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isChatReadOnly, [context, chatRoomId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> cleanupOldHangoutChats() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldHangoutChats, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i5.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateUserProfile({
    required String? userId,
    String? displayName,
    String? photoUrl,
    String? bio,
    int? age,
    String? location,
    List<String>? interests,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #userId: userId,
              #displayName: displayName,
              #photoUrl: photoUrl,
              #bio: bio,
              #age: age,
              #location: location,
              #interests: interests,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.UserModel>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i4.Future<List<_i6.UserModel>>.value(
              <_i6.UserModel>[],
            ),
          )
          as _i4.Future<List<_i6.UserModel>>);

  @override
  _i4.Future<_i6.UserModel?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<_i6.UserModel?>.value(),
          )
          as _i4.Future<_i6.UserModel?>);

  @override
  _i4.Future<void> removeMemberFromPost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMemberFromPost, [postId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [FeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackService extends _i1.Mock implements _i7.FeedbackService {
  MockFeedbackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createFeedbackPromptForAuthor(_i8.Post? completedPost) =>
      (super.noSuchMethod(
            Invocation.method(#createFeedbackPromptForAuthor, [completedPost]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i9.PendingFeedbackPrompt>> getPendingFeedbackPrompts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingFeedbackPrompts, [userId]),
            returnValue: _i4.Stream<List<_i9.PendingFeedbackPrompt>>.empty(),
          )
          as _i4.Stream<List<_i9.PendingFeedbackPrompt>>);

  @override
  _i4.Future<void> markPromptAsShown(String? promptId) =>
      (super.noSuchMethod(
            Invocation.method(#markPromptAsShown, [promptId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasAuthorProvidedFeedback(
    String? hangoutId,
    String? authorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasAuthorProvidedFeedback, [
              hangoutId,
              authorId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> submitFeedback({
    required String? hangoutId,
    required String? userId,
    required bool? didMeetup,
    String? additionalFeedback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitFeedback, [], {
              #hangoutId: hangoutId,
              #userId: userId,
              #didMeetup: didMeetup,
              #additionalFeedback: additionalFeedback,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getFeedbackStats() =>
      (super.noSuchMethod(
            Invocation.method(#getFeedbackStats, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> cleanupOldPendingPrompts() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupOldPendingPrompts, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.MeetupFeedback>> getFeedbackForHangout(
    String? hangoutId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedbackForHangout, [hangoutId]),
            returnValue: _i4.Future<List<_i9.MeetupFeedback>>.value(
              <_i9.MeetupFeedback>[],
            ),
          )
          as _i4.Future<List<_i9.MeetupFeedback>>);

  @override
  _i4.Future<void> createTestFeedbackPrompts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#createTestFeedbackPrompts, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearTestFeedbackPrompts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearTestFeedbackPrompts, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i10.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> isConsentGiven() =>
      (super.noSuchMethod(
            Invocation.method(#isConsentGiven, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void disable() => super.noSuchMethod(
    Invocation.method(#disable, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> trackHangoutCreated({
    required String? userId,
    required String? hangoutId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackHangoutCreated, [], {
              #userId: userId,
              #hangoutId: hangoutId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackHangoutJoined({
    required String? userId,
    required String? hangoutId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackHangoutJoined, [], {
              #userId: userId,
              #hangoutId: hangoutId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMeetupSuccess({
    required bool? didMeetup,
    required String? hangoutId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMeetupSuccess, [], {
              #didMeetup: didMeetup,
              #hangoutId: hangoutId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackUserSignUp({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#trackUserSignUp, [], {#userId: userId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i11.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onTokenRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onTokenRefresh, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void initializeTokenRefresh() => super.noSuchMethod(
    Invocation.method(#initializeTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> removeToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getCurrentToken() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unsubscribeFromTopics(List<String>? topics) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopics, [topics]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> subscribeToHangoutTopicsBasedOnGender(String? gender) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToHangoutTopicsBasedOnGender, [gender]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> subscribeToGenderSpecificTopic(String? gender) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToGenderSpecificTopic, [gender]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void initializeMessageHandlers() => super.noSuchMethod(
    Invocation.method(#initializeMessageHandlers, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> notifyHangoutOwnerOfJoin({
    required String? hangoutId,
    required String? ownerId,
    required String? joinerName,
    required String? joinerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutOwnerOfJoin, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #joinerName: joinerName,
              #joinerId: joinerId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> notifyHangoutOwnerOfLeave({
    required String? hangoutId,
    required String? ownerId,
    required String? leaverName,
    required String? leaverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutOwnerOfLeave, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #leaverName: leaverName,
              #leaverId: leaverId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> notifyHangoutUpdated({
    required String? hangoutId,
    required String? ownerId,
    required List<String>? participantIds,
    required List<String>? changes,
    String? oldDescription,
    DateTime? oldTime,
    String? oldLocation,
    String? newDescription,
    DateTime? newTime,
    String? newLocation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutUpdated, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #participantIds: participantIds,
              #changes: changes,
              #oldDescription: oldDescription,
              #oldTime: oldTime,
              #oldLocation: oldLocation,
              #newDescription: newDescription,
              #newTime: newTime,
              #newLocation: newLocation,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleHangoutChatNotifications(
    String? hangoutId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleHangoutChatNotifications, [
              hangoutId,
              enabled,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getHangoutChatNotificationPreference(String? hangoutId) =>
      (super.noSuchMethod(
            Invocation.method(#getHangoutChatNotificationPreference, [
              hangoutId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
