// Mocks generated by Mockito 5.4.6 from annotations
// in squad_app/test/unit/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i10;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:firebase_storage/firebase_storage.dart' as _i11;
import 'package:image_picker/image_picker.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:squad_app/models/user_model.dart' as _i5;
import 'package:squad_app/services/account_deletion_service.dart' as _i7;
import 'package:squad_app/services/auth_service.dart' as _i2;
import 'package:squad_app/services/notification_service.dart' as _i6;
import 'package:squad_app/services/storage_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i5.UserModel?> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<_i5.UserModel?> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<_i5.UserModel?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<_i5.UserModel?> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.UserModel?> getUserData(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [uid]),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<void> updateUserProfile({
    String? displayName,
    String? photoUrl,
    String? bio,
    String? classYear,
    String? location,
    List<String>? interests,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #displayName: displayName,
              #photoUrl: photoUrl,
              #bio: bio,
              #classYear: classYear,
              #location: location,
              #interests: interests,
              #gender: gender,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isUsernameAvailable(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#isUsernameAvailable, [username]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> reauthenticateWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithGoogle, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> reauthenticateWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithApple, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> reauthenticateUser() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateUser, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> onTokenRefresh() =>
      (super.noSuchMethod(
            Invocation.method(#onTokenRefresh, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void initializeTokenRefresh() => super.noSuchMethod(
    Invocation.method(#initializeTokenRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> removeToken() =>
      (super.noSuchMethod(
            Invocation.method(#removeToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getCurrentToken() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unsubscribeFromTopics(List<String>? topics) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopics, [topics]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToHangoutTopicsBasedOnGender(String? gender) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToHangoutTopicsBasedOnGender, [gender]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToGenderSpecificTopic(String? gender) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToGenderSpecificTopic, [gender]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void initializeMessageHandlers() => super.noSuchMethod(
    Invocation.method(#initializeMessageHandlers, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> notifyHangoutOwnerOfJoin({
    required String? hangoutId,
    required String? ownerId,
    required String? joinerName,
    required String? joinerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutOwnerOfJoin, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #joinerName: joinerName,
              #joinerId: joinerId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyHangoutOwnerOfLeave({
    required String? hangoutId,
    required String? ownerId,
    required String? leaverName,
    required String? leaverId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutOwnerOfLeave, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #leaverName: leaverName,
              #leaverId: leaverId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> notifyHangoutUpdated({
    required String? hangoutId,
    required String? ownerId,
    required List<String>? participantIds,
    required List<String>? changes,
    String? oldDescription,
    DateTime? oldTime,
    String? oldLocation,
    String? newDescription,
    DateTime? newTime,
    String? newLocation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#notifyHangoutUpdated, [], {
              #hangoutId: hangoutId,
              #ownerId: ownerId,
              #participantIds: participantIds,
              #changes: changes,
              #oldDescription: oldDescription,
              #oldTime: oldTime,
              #oldLocation: oldLocation,
              #newDescription: newDescription,
              #newTime: newTime,
              #newLocation: newLocation,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleHangoutChatNotifications(
    String? hangoutId,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleHangoutChatNotifications, [
              hangoutId,
              enabled,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getHangoutChatNotificationPreference(String? hangoutId) =>
      (super.noSuchMethod(
            Invocation.method(#getHangoutChatNotificationPreference, [
              hangoutId,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [AccountDeletionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountDeletionService extends _i1.Mock
    implements _i7.AccountDeletionService {
  MockAccountDeletionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> revokeNotificationTokens(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeNotificationTokens, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> revokeAppleSignInToken(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeAppleSignInToken, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<String> deleteUserAccount(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAccount, [userId]),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Future<bool> hasActiveSubscriptions(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveSubscriptions, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> scheduleAccountDeletion(
    String? userId,
    DateTime? deletionDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleAccountDeletion, [userId, deletionDate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelScheduledDeletion(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelScheduledDeletion, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i8.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> uploadProfileImage(
    String? userId,
    _i9.XFile? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [userId, imageFile]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> uploadGroupImage(String? groupId, _i9.XFile? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGroupImage, [groupId, imageFile]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> uploadMessageImage(
    String? groupId,
    _i9.XFile? imageFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMessageImage, [groupId, imageFile]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> uploadFile(
    String? groupId,
    _i10.File? file,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [groupId, file, fileName]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i9.XFile?> pickImageFromGallery() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromGallery, []),
            returnValue: _i3.Future<_i9.XFile?>.value(),
          )
          as _i3.Future<_i9.XFile?>);

  @override
  _i3.Future<_i9.XFile?> pickImageFromCamera() =>
      (super.noSuchMethod(
            Invocation.method(#pickImageFromCamera, []),
            returnValue: _i3.Future<_i9.XFile?>.value(),
          )
          as _i3.Future<_i9.XFile?>);

  @override
  _i3.Future<List<_i9.XFile>?> pickMultipleImages() =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleImages, []),
            returnValue: _i3.Future<List<_i9.XFile>?>.value(),
          )
          as _i3.Future<List<_i9.XFile>?>);

  @override
  _i3.Future<void> deleteFile(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [url]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteOldProfileImage(String? oldPhotoUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOldProfileImage, [oldPhotoUrl]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i11.UploadTask? uploadFileWithProgress(String? path, _i10.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFileWithProgress, [path, file]),
          )
          as _i11.UploadTask?);

  @override
  _i3.Stream<_i11.TaskSnapshot> uploadWithProgress(
    String? groupId,
    _i10.File? file,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadWithProgress, [groupId, file, fileName]),
            returnValue: _i3.Stream<_i11.TaskSnapshot>.empty(),
          )
          as _i3.Stream<_i11.TaskSnapshot>);
}
