// Mocks generated by Mockito 5.4.6 from annotations
// in squad_app/test/unit/providers/post_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:squad_app/models/block_model.dart' as _i8;
import 'package:squad_app/models/post_model.dart' as _i4;
import 'package:squad_app/models/user_model.dart' as _i7;
import 'package:squad_app/services/block_service.dart' as _i6;
import 'package:squad_app/services/post_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostService extends _i1.Mock implements _i2.PostService {
  MockPostService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createPost(_i4.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [post]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createPost, [post]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Stream<List<_i4.Post>> getPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, []),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Stream<List<_i4.Post>> getAllPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPosts, []),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Stream<List<_i4.Post>> getPostsByStatus(_i4.PostStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByStatus, [status]),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Stream<List<_i4.Post>> getUserPosts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPosts, [userId]),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Stream<List<_i4.Post>> getUpcomingPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingPosts, []),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Stream<List<_i4.Post>> getOngoingPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getOngoingPosts, []),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Future<void> joinPost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinPost, [postId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> leavePost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#leavePost, [postId, userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePost(_i4.Post? post) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [post]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> doesAuthorNeedFeedbackForDeletion(
    String? postId,
    String? authorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doesAuthorNeedFeedbackForDeletion, [
              postId,
              authorId,
            ]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> deletePostWithFeedback(
    String? postId,
    String? authorId, {
    bool? authorDidMeetup,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deletePostWithFeedback,
              [postId, authorId],
              {#authorDidMeetup: authorDidMeetup},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> lockPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#lockPost, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unlockPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlockPost, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Post?> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i3.Future<_i4.Post?>.value(),
          )
          as _i3.Future<_i4.Post?>);

  @override
  _i3.Stream<List<_i4.Post>> searchPosts(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchPosts, [query]),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Stream<List<_i4.Post>> getPostsByGenderPreference(String? userGender) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByGenderPreference, [userGender]),
            returnValue: _i3.Stream<List<_i4.Post>>.empty(),
          )
          as _i3.Stream<List<_i4.Post>>);

  @override
  _i3.Future<void> updatePostStatuses() =>
      (super.noSuchMethod(
            Invocation.method(#updatePostStatuses, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BlockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockService extends _i1.Mock implements _i6.BlockService {
  MockBlockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> blockUser(String? targetUserId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [targetUserId], {#reason: reason}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unblockUser(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockUser, [targetUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isBlocked(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlocked, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isBlockedBy(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockedBy, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isBlockingRelationship(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockingRelationship, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<_i7.UserModel>> getBlockedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedUsers, []),
            returnValue: _i3.Future<List<_i7.UserModel>>.value(
              <_i7.UserModel>[],
            ),
          )
          as _i3.Future<List<_i7.UserModel>>);

  @override
  _i3.Stream<List<_i8.BlockModel>> getBlocksStream() =>
      (super.noSuchMethod(
            Invocation.method(#getBlocksStream, []),
            returnValue: _i3.Stream<List<_i8.BlockModel>>.empty(),
          )
          as _i3.Stream<List<_i8.BlockModel>>);

  @override
  List<_i7.UserModel> filterBlockedUsers(
    List<_i7.UserModel>? users,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterBlockedUsers, [
              users,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: <_i7.UserModel>[],
          )
          as List<_i7.UserModel>);

  @override
  bool shouldFilterContent(
    String? authorId,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldFilterContent, [
              authorId,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldCensorContent(
    String? authorId,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldCensorContent, [
              authorId,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldHideHangoutFromBlocked(
    String? hangoutHostId,
    List<String>? blockedUserIds,
    List<String>? blockedByUserIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shouldHideHangoutFromBlocked, [
              hangoutHostId,
              blockedUserIds,
              blockedByUserIds,
            ]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<bool> canAccessHangout(String? hangoutHostId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#canAccessHangout, [hangoutHostId, userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
